### ISSUE TITLE
Add all other models

### ISSUE THREAD

**Issue by SoptikHa2** [FIT-FIKS/web#3]
See documentation.

So far, this needs to be created:
![image](https://user-images.githubusercontent.com/24734779/172579968-6ef26fa5-8783-4533-86ae-9b065e099ad0.png)

Only season is made, and reference to Round is still missing.

**Comment by SoptikHa2** [comment]
- add models as c# classes
- refactoring: rename `SeasonContext` to `FiksDBContext` or something like that
- add DbSets to the context
- generate database migration (see contributing.md)

**Comment by MistrMxyzptlk** [comment]
- Added school
- Added user from ASP .NET identity Framework
- Added userLogin from ASP .NET indentity Framework
- Added UserToken from ASP .NET indentity Framework

the last two will have to be added to the schema. I have removed all the unneeded parts of identity framework, but those almost have to be there. (It would be dum to remove them and could couse some issues)
